config/routes.rb
Citybee::Application.routes.draw do

  root  :to => "deals#show"
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }
  devise_scope :user do 
    match '/auth/:provider' => 'users/omniauth_callbacks#passthru'
  end
  resources :deals

  
  match "/home/myaccount" => "account#index"
  match "/home/markasused/:id/used=:used" => "deals#markasused"
  match "/dailydeal" => "deals#show"
  match "/download" => "users#download"
  match "/sting=:id" => "users#influenced"
  match "/whyus" => "extras#whyus"

end

app/models/deal.rb
class Deal < ActiveRecord::Base
  attr_accessible :title, :min_needed, :max_allowed, :end_at, :summary, :fine_print, :offers_attributes, :locations_attributes, :featured_deal, :image_name
  has_many :locations, :dependent => :destroy
  has_many :offers, :dependent => :destroy
  has_many :downloads
  has_many :users, :through => :downloads



  accepts_nested_attributes_for :offers, :reject_if => lambda {|a| a[:title].blank?}, :allow_destroy => true
  accepts_nested_attributes_for :locations, :reject_if => lambda {|a| a[:street_1].blank?}, :allow_destroy => true
end

app/controllers/deals_controller.rb
class DealsController < ApplicationController
  def new
    @deal = Deal.new
    2.times { @deal.offers.build }
    2.times { @deal.locations.build }
  end

  def markasused 
    user = session[:user]
    #make sure the passed offer id belongs to logged in user
    puts params[:id]
    download_entry = user.downloads.find_by_offer_id(params[:id])
    if download_entry != nil
      if params[:used] == "used"
        download_entry.marked_used = Time.now
        download_entry.save
      elsif params[:used] == "unused"
        download_entry.marked_used = nil
        download_entry.save
      end
    end
    redirect_to "/home/myaccount"
  end


  def create
    @deal = Deal.new(params[:deal])
    if @deal.save
      redirect_to deals_url, :notice => "Successfully created deal."
    else
      render :action => 'new'
    end
  end

  def edit
    @deal = Deal.find(params[:id])
  end

  def update
    @deal= Deal.find(params[:id])
    if @deal.update_attributes(params[:deal])
      redirect_to "/deals", :notice  => "Successfully updated deal."
    else
      render :action => 'edit'
    end
  end

  def index
    @deals = Deal.all
  end

  def show
    puts session[:sting]
    if params[:id] == nil
      @deal = Deal.where(:featured_deal => true).order("updated_at desc").first
      @deals = Deal.where(:featured_deal => false)
    else
      @deal = Deal.find(params[:id])
      @deals = Deal.where("id <> ?", params[:id])
    end
  end
end

app/helpers/deal_helper.rb
module DealHelper
end

app/helpers/deals_helper.rb
module DealsHelper
end

app/views/deals/edit.html.haml
#big-box.border-radius
  #header
    %h1 Add new deal
  #new-deals
    #deal-info
      %h2 Deal Info
      = form_for @deal do |f|
        = errors_for(@deal, "Oops, unable to add new deal").html_safe
        %ul.clearfix
          %li.label
            = f.label :title
          %li.field
            = f.text_field :title
          %li.label
            = f.label :image_name
          %li.field
            = f.text_field :image_name
        %ul.clearfix
          %li.label
            = f.label "Featured Deal"
          %li.field
            = f.radio_button :featured_deal, true
            = f.label :featured_Deal, "Feature", :value => 'yes'
            = f.radio_button :featured_deal, false
            = f.label :featured_Deal, "Don't Feature", :value => 'no'
        %ul.clearfix
          %li.label
            = f.label :min_needed
          %li.field
            = f.text_field :min_needed, :size => 5
        %ul.clearfix
          %li.label
            = f.label :max_allowed
          %li.field
            = f.text_field :max_allowed
        %ul.clearfix
          %li.label
            = f.label :end_at
          %li.field
            = f.datetime_select :end_at
        %ul.clearfix
          %li.label
            = f.label :summary
          %li.field
            = f.text_area :summary, :rows => 5
        %ul.clearfix
          %li.label
            = f.label :fine_print
          %li.field
            = f.text_area :fine_print, :rows=> 5
        - f.fields_for :locations do |builder|
          %ul.clearfix
            %li.label
              %b 
                = builder.label "Street"
            %li.field
              = builder.text_field :street_1
          %ul.clearfix
            %li.label
              = builder.label "Street 2"
            %li.field
              = builder.text_field :street_2
          %ul.clearfix
            %li.label
              = builder.label "City"
            %li.field
              = builder.text_field :city
          %ul.clearfix
            %li.label
              = builder.label "State"
            %li.field
              = builder.text_field :state
          %ul.clearfix
            %li.label
              = builder.label "Zip"
            %li.field
              = builder.text_field :zip
        - f.fields_for :offers do |builder|
          %ul.clearfix
            %li.label
              %b 
                = builder.label "Offer"
            %li.field
              = builder.text_field :title
          %ul.clearfix
            %li.label
              = builder.label "Paying Price"
            %li.field
              = builder.text_field :price
          %ul.clearfix
            %li.label
              = builder.label "Actual Value"
            %li.field
              = builder.text_field :value
        %ul.clearfix
          %li.label
          %li.field
            %button Add

app/views/deals/index.html.haml
#big-box.border-radius
  #header
    %h1
      all deals
  %table
    %tr
      %th Title
      %th End At
      %th Min
      %th Max
    - for deal in @deals
      %tr
        %td 
          =deal.title
        %td 
          = time_diff_in_natural_language(Time.now, deal.end_at)
        %td 
          =deal.min_needed
        %td 
          =deal.max_allowed
        %td
          =link_to "Edit", edit_deal_path(deal)

app/views/deals/new.html.haml
#big-box.border-radius
  #header
    %h1 Add new deal
  #new-deals
    #deal-info
      %h2 Deal Info
      = form_for @deal do |f|
        = errors_for(@deal, "Oops, unable to add new deal").html_safe
        %ul.clearfix
          %li.label
            = f.label :title
          %li.field
            = f.text_field :title
          %li.label
            = f.label :image_name
          %li.field
            = f.text_field :image_name
        %ul.clearfix
          %li.label
            = f.label "Featured Deal"
          %li.field
            = f.radio_button :featured_deal, true
            = f.label :featured_Deal, "Feature", :value => 'yes'
            = f.radio_button :featured_deal, false
            = f.label :featured_Deal, "Don't Feature", :value => 'no'
        %ul.clearfix
          %li.label
            = f.label :min_needed
          %li.field
            = f.text_field :min_needed, :size => 5
        %ul.clearfix
          %li.label
            = f.label :max_allowed
          %li.field
            = f.text_field :max_allowed
        %ul.clearfix
          %li.label
            = f.label :end_at
          %li.field
            = f.datetime_select :end_at
        %ul.clearfix
          %li.label
            = f.label :summary
          %li.field
            = f.text_area :summary, :rows => 5
        %ul.clearfix
          %li.label
            = f.label :fine_print
          %li.field
            = f.text_area :fine_print, :rows=> 5
        - f.fields_for :locations do |builder|
          %ul.clearfix
            %li.label
              %b 
                = builder.label "Street"
            %li.field
              = builder.text_field :street_1
          %ul.clearfix
            %li.label
              = builder.label "Street 2"
            %li.field
              = builder.text_field :street_2
          %ul.clearfix
            %li.label
              = builder.label "City"
            %li.field
              = builder.text_field :city
          %ul.clearfix
            %li.label
              = builder.label "State"
            %li.field
              = builder.text_field :state
          %ul.clearfix
            %li.label
              = builder.label "Zip"
            %li.field
              = builder.text_field :zip
        - f.fields_for :offers do |builder|
          %ul.clearfix
            %li.label
              %b 
                = builder.label "Offer"
            %li.field
              = builder.text_field :title
          %ul.clearfix
            %li.label
              = builder.label "Paying Price"
            %li.field
              = builder.text_field :price
          %ul.clearfix
            %li.label
              = builder.label "Actual Value"
            %li.field
              = builder.text_field :value
        %ul.clearfix
          %li.label
          %li.field
            %button Add

app/views/deals/show.html.haml
#big-box.border-radius
  #header
    %h1
      Featured Deal
  #two-col
    #right
      #deal-title
        %h1 
          = @deal.title
      #multiple-offers
        #bounty
          #offers
            - @deal.offers.each_with_index do |offer, index|
              - if index == 0
                #deals.horizontalLineBottom
                  %h3 
                    = offer.title 
                  %dl
                    %dt You Pay:
                    %dd 
                      $
                      =offer.price 
                    %dt Value
                    %dd 
                      $
                      =offer.value 
              - else
                #deals.horizontalLine.second
                  %h3 
                    = offer.title 
                  %dl
                    %dt You Pay:
                    %dd 
                      $
                      =offer.price 
                    %dt Value
                    %dd 
                      $
                      =offer.value 
          #buywrap
            = form_tag "/download" do
              = hidden_field_tag(:deal_id, @deal.id)
              = hidden_field_tag(:offer_id, @deal.offers.first.id)
              %button 
                Get it!
        %ul.deal-stats
          %li 
            .value.tip
              %a{:href=>"#"} tip this deal
              /%img{:style=>"",:src=>"http://assets1.grouponcdn.com/images/groupon/icons/tipometer/check_mark.png"}
            .label 
          %li 
            .value 500
            .label grabbed
          %li.last
            .value 
              = time_diff_in_natural_language(Time.now, @deal.end_at)
            .label remaining
      #deal-desc.clearfix
        =@deal.summary
    #left
      .deal-image{:style=>"background: url('/images/#{@deal.image_name}') no-repeat scroll left top #EFEFEF"}
    #bottom 
      #fine-print
        %h2 the fine print
        %p 
          =@deal.fine_print
      #locations
        %h2 locations
        %ul.address
          %li
            %span.street 
              =@deal.locations.first.street_1 if @deal.locations.size > 0
            %br
            %span.phone  
              =@deal.locations.first.phone if @deal.locations.size > 0
            |
            %span.directions
              %a{:href=>"#"} get directions
          - if @deal.locations.count == 2
            %li
              %span.street 1234 Fake Street
              %br
              %span.phone 703-545-3434 
              |
              %span.directions
                %a{:href=>"#"} get directions

#big-box.border-radius
  #header
    %h1
      other deals
  #otherdeals
    #related
      - for deal in @deals
        - @class= cycle("", "middle")
        .deal-item.col{:class => (@class)}
          #inside.border-radius
            .view-image
              %a{:href=>"/deals/#{deal.id}"}
                %img{:src=>"/images/#{deal.image_name}", :width=>"190px", :height=>"200px"}
            .deal-title
              %h2
                %a{:href=>"/deals/#{deal.id}"}
                  =deal.title
              %p.deal
              %dl
                %dt You Pay:
                %dd 
                  $
                  =deal.offers.first.price 
                %dt Value
                %dd 
                  $
                  =deal.offers.first.value